name: code-signing
run-name: Code Signing
on:
  pull_request_review:
    types:
      - submitted
  merge_group:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  code-signing-labeler:
    name: code-signing-labeler
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Label Pull Request
        uses: actions/labeler@v6

  code-signing:
    name: code-signing
    needs: code-signing-labeler
    permissions:
      contents: write
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    runs-on: windows-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v6
          with:
            ref: ${{ github.event.pull_request.head.ref }}
        - name: Install Microsoft SignTool
          shell: pwsh
          run: .github/scripts/Install-MicrosoftSignTool.ps1 -Latest
        - name: Sign Office Macros
          if:  contains(github.event.pull_request.labels.*.name, 'office-macros')
          shell: pwsh
          run: .github/scripts/CodeSigning.ps1 -ClientId '${{ secrets.CODE_SIGNING_CLIENTID }}' -TenantId '${{ secrets.CODE_SIGNING_TENANTID }}' -KeyVaultUrl '${{ vars.CODE_SIGNING_KEYVAULT }}' -RootCert '${{ secrets.ROOT_CERT }}' -Password '${{ secrets.CODE_SIGNING_CLIENTSECRET }}' -CertName '${{ vars.CODE_SIGNING_CERT_NAME }}' -Path '.\Office'
        - name: Commit changes to GitHub
          run: |
            git config --local user.email "github-actions@github.com"
            git config --local user.name "GitHub Actions Code Signing"
            git add *
            git commit -m "GitHub Action HMCTS RCJ Cactus macros signed"
            git push
