name: office-macro-signing
run-name: Office Macro Signing
on:
  push:
    branches:
      - main
    paths:
      - 'Office/**.docm'
      - 'Office/**.dotm'
      - 'Office/**.pptm'
      - 'Office/**.potm'
      - 'Office/**.ppsm'
      - 'Office/**.ppam'
      - 'Office/**.xlsm'
      - 'Office/**.xltm'

jobs:
  office-macro-signing:
    name: office-macro-signing
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v6
          with:
            token: ${{ secrets.CODE_SIGNING_PAT }}
            ref: ${{ github.head_ref }}
        - name: Install Microsoft SignTool
          shell: pwsh
          run: .github/scripts/Install-MicrosoftSignTool.ps1 -Latest
        - name: Sign Office Macros
          shell: pwsh
          run: .github/scripts/CodeSigning.ps1 -ClientId '${{ secrets.CODE_SIGNING_CLIENTID }}' -TenantId '${{ secrets.CODE_SIGNING_TENANTID }}' -KeyVaultUrl '${{ vars.CODE_SIGNING_KEYVAULT }}' -RootCert '${{ secrets.ROOT_CERT }}' -Password '${{ secrets.CODE_SIGNING_CLIENTSECRET }}' -CertName '${{ vars.CODE_SIGNING_CERT_NAME }}' -Path 'Office' -FileExtension '.docm','.dotm','.pptm','.potm','.ppsm','.ppam','.xlsm','.xltm'
        - name: Commit changes to GitHub
          run: |
            git config --local user.name "GitHub Actions[bot]"
            git config --local user.email "github-actions@users.noreply.github.com"
            git add *
            git commit -m "GitHub Action Office macros signed"
            git push
