name: office-macro-signing
run-name: Office Macro Signing Action
on: [pull_request]
jobs:
    office-macro-signing:
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6
            - name: Install Microsoft SignTool
              run: .github/scripts/Install-MicrosoftSignTool.ps1
              shell: pwsh
            - name: Sign Office Macros
              run: .github/scripts/OfficeMacroSigning.ps1 -Base64Cert ${{ secrets.CODE_SIGNING_CERT }} -Password ${{ secrets.CODE_SIGNING_SECRET }}
              shell: pwsh
            - name: Commit changes to GitHub
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add *
                git commit -m "Signed office macros"
                git push origin ${{ github.ref }}
